services:
  - type: web
    name: mallempu-fplbot
    runtime: docker
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: FPL_ID
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
    healthCheckPath: /api/health
